export const CRAWL_QUEUE_CONSTANTS = {
	DOMAIN_CACHE_CLEANUP_THRESHOLD: 500,
	DOMAIN_ENTRY_EXPIRY_MS: 60000,
	DEFAULT_SLEEP_MS: 100,
	MIN_SLEEP_MS: 50,
} as const;

export const DYNAMIC_RENDERER_CONSTANTS = {
	COMPLEX_JS_SITES: [
		"youtube.com",
		"google.com",
		"facebook.com",
		"meta.com",
		"twitter.com",
		"x.com",
		"instagram.com",
		"linkedin.com",
		"discord.com",
		"reddit.com",
		"pinterest.com",
		"tiktok.com",
		"netflix.com",
		"amazon.com",
		"airbnb.com",
		"uber.com",
		"spotify.com",
		"github.com",
		"stackoverflow.com",
		"medium.com",
		"twitch.tv",
		"salesforce.com",
		"slack.com",
		"notion.so",
		"figma.com",
		"canva.com",
		"trello.com",
		"asana.com",
		"dropbox.com",
		"zoom.us",
	],
	VIEWPORT: { width: 1280, height: 720 },
	RECYCLE_THRESHOLD: {
		DEFAULT: 200,
		RENDER_ENV: 50,
	},
	TIMEOUTS: {
		COMPLEX_NAVIGATION: 60000,
		STANDARD_NAVIGATION: 30000,
		SELECTOR_WAIT: 15000,
		ADDITIONAL_WAIT: 2000,
	},
} as const;
