import { CRAWL_PAGE_SNAPSHOT_LIMIT } from "../shared/contracts/index.js";

export const UI_LIMITS = {
	MAX_PAGE_BUFFER: CRAWL_PAGE_SNAPSHOT_LIMIT,
	MAX_LOGS: 100,
} as const;

export const TOAST_DEFAULTS = {
	DEFAULT_TIMEOUT: 3000,
	LONG_TIMEOUT: 5000,
	EXIT_ANIMATION_MS: 300,
} as const;

export const SEQUENCE_TIMINGS = {
	COUNT_1: 5400,
	COUNT_2: 6650,
	COUNT_3: 7800,
	READY: 8900,
	COMPLETE: 10200,
};
